import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Terms of Service', description: 'SnapTools terms of service.' };

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 prose prose-gray">
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> February 2026</p>
      <p>By using SnapTools (&quot;the Service&quot;), you agree to these Terms of Service. Please read them carefully.</p>

      <h2>Use of Service</h2>
      <p>SnapTools provides free online utility tools for personal and commercial use. All tools process data locally in your browser. You may use the tools for any lawful purpose.</p>

      <h2>No Warranties</h2>
      <p>The Service is provided &quot;as is&quot; without warranties of any kind, either express or implied. We do not guarantee that the tools will be error-free, uninterrupted, or that results will be accurate for all use cases.</p>

      <h2>Limitation of Liability</h2>
      <p>SnapTools shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Service. You use all tools at your own risk.</p>

      <h2>Intellectual Property</h2>
      <p>The SnapTools website, design, and content are owned by us. You may not copy, modify, or distribute our website content without permission. The output generated by our tools belongs to you.</p>

      <h2>Prohibited Uses</h2>
      <p>You may not use the Service to: (a) violate any laws; (b) attempt to gain unauthorized access to our systems; (c) use automated tools to scrape or overload the website.</p>

      <h2>Changes to Terms</h2>
      <p>We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

      <h2>Contact</h2>
      <p>Questions about these terms? Visit our <a href="/contact">Contact page</a>.</p>
    </div>
  );
}
